import type { CatalogFile } from "../../src/types/catalog";

export const e2eCatalog = {
  schemaVersion: 1,
  generatedAt: "2026-08-09T00:00:00.000Z",
  sourceChannelId: "e2e-fixture",
  movieCount: 2,
  movies: [
    {
      videoId: "e2eMovie001",
      title: "Naruto's Complete Journey (Full Movie)",
      description: "A deterministic full movie used by the browser acceptance suite.",
      publishedAt: "2026-08-01T14:00:00.000Z",
      durationSeconds: 7_200,
      thumbnails: {},
      categories: ["naruto"],
    },
    {
      videoId: "e2eVaderMovie001",
      title: "What If Darth Vader Overthrew The Emperor? (Full Movie)",
      description: "A deterministic full movie from Vader's Order.",
      publishedAt: "2026-08-05T14:00:00.000Z",
      durationSeconds: 8_000,
      thumbnails: {},
      categories: ["star-wars"],
      channelHandle: "@vadersorder",
      channelName: "Vader's Order",
      isExtended: true,
    },
  ],
  showCount: 1,
  shows: [
    {
      showId: "show-what-if-naruto-left-konoha-demo0001",
      title: "What If Naruto Left Konoha",
      description: "Naruto leaves the village and faces an unfamiliar future.",
      latestPublishedAt: "2026-08-03T14:00:00.000Z",
      thumbnails: { maxres: "data:image/svg+xml,%3Csvg%20id='e2e-feature'%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%209'%3E%3Crect%20width='16'%20height='9'%20fill='%234a090d'/%3E%3C/svg%3E" },
      categories: ["naruto"],
      seasonNumber: 1,
      episodes: [
        {
          videoId: "sNarutoE001",
          title: "What If Naruto Left Konoha Part 1",
          description: "Naruto begins a different journey beyond the Hidden Leaf.",
          publishedAt: "2026-08-02T14:00:00.000Z",
          durationSeconds: 1_800,
          thumbnails: {},
          episodeNumber: 1,
          episodeLabel: "Episode 1",
        },
        {
          videoId: "sNarutoE002",
          title: "What If Naruto Left Konoha Final",
          description: "The story reaches its conclusion.",
          publishedAt: "2026-08-03T14:00:00.000Z",
          durationSeconds: 1_900,
          thumbnails: {},
          episodeNumber: 2,
          episodeLabel: "Final",
        },
      ],
    },
  ],
} satisfies CatalogFile;
